version: "3"

services:

  server:

    build:
      context: .
      dockerfile: DockerfileServer

    ports:
      - 8090:8090

  client:

    build:
      context: .
      dockerfile: DockerfileClient

    network_mode: "host"

    depends_on:
      - server